services:
  _defaults:
    autowire: true
    autoconfigure: true

  AlexTanVer\ElasticBundle\Command\IndexCreateCommand:
    class: AlexTanVer\ElasticBundle\Command\IndexCreateCommand
    arguments:
      - '@AlexTanVer\ElasticBundle\Factory\ElasticIndexFactory'
      - '@AlexTanVer\ElasticBundle\ClientBuilder'
      - '@AlexTanVer\ElasticBundle\Service\IndexService'

  AlexTanVer\ElasticBundle\Command\IndexUpdateCommand:
    class: AlexTanVer\ElasticBundle\Command\IndexUpdateCommand
    arguments:
      - '@AlexTanVer\ElasticBundle\Factory\ElasticIndexFactory'
      - '@AlexTanVer\ElasticBundle\ClientBuilder'
      - '@AlexTanVer\ElasticBundle\Service\IndexService'

  AlexTanVer\ElasticBundle\Command\IndexRecreateCommand:
    class: AlexTanVer\ElasticBundle\Command\IndexRecreateCommand
    arguments:
      - '@AlexTanVer\ElasticBundle\Factory\ElasticIndexFactory'
      - '@AlexTanVer\ElasticBundle\ClientBuilder'
      - '@AlexTanVer\ElasticBundle\Service\IndexService'

  AlexTanVer\ElasticBundle\Command\UpdateSingleIndexCommand:
    class: AlexTanVer\ElasticBundle\Command\UpdateSingleIndexCommand
    arguments:
      - '@AlexTanVer\ElasticBundle\Factory\ElasticIndexFactory'
      - '@AlexTanVer\ElasticBundle\ClientBuilder'
      - '@jms_serializer.serializer'

  AlexTanVer\ElasticBundle\Command\GenerateDocumentCommand:
    class: AlexTanVer\ElasticBundle\Command\GenerateDocumentCommand
    arguments:
      - 'elastic:document:generate'
      - '@kernel'

